### ISSUE TITLE
Only first color used when passed an array of string hex values

### ISSUE THREAD

**Issue by return-null** [mattetti/googlecharts#77]
If I set:

:bar_colors => ["81284a","b2884f","d61e49","32e2fa","a78811","8ca43c","f66980"]

Then I find that all the bars on the graph are drawn using the frist hex value. That is, they are all this color. The legend will actually show each of the colors, but not the graph itself. Tried using :stacked => false, but that had no effect. Not sure if I am doing something wrong, or if there has been a change in the Google API which has not been accounted for?

**Comment by zukunftsalick** [comment]
Can you share your code snippet? @return-null

**Comment by return-null** [comment]
Here's the code:
            my_chart_url = Gchart.send(
                chart_type,
                :size => size, 
                :title => title,
                :bg => bg, 
                :legend => legend, 
                :data => data, 
                chart_colors.to_sym => colours
            )

It doesn't matter if it to literally say bar_colors = ["52642e","7f999c","ebe749","d67234","e1dfe7","ebea96","d2462b"]

The effect is the same. But it may be submitting it to Google correctly. Here's part of a URL generated:
http://chart.apis.google.com/chart?chco=81284a,b2884f,d61e49,32e2fa,a78811,8ca43c,f66980&....

I can't actually see the what the issue is. This might be a problem/change with Google's API?

**Comment by zukunftsalick** [comment]
I guess you might be having a different size on the `data` parameter. Check the following example below which worked fine:

```
Gchart.bar( :data => [[1,2,4,67,100,41,234],[45,23,67,12,67,300, 250], [12,13,2,5,17,12,22], [52,13,2,15,71,132,92]], 
            :title => 'SD Ruby Fu level', 
            :legend => ['matt','patrick', 'tim', 'marc'], 
            :bg => {:color => '76A4FB', :type => 'gradient'}, 
            :bar_colors => ['ff0000','00ff00','aa00ff','99FF00'])
```

You can check the graph at http://chart.apis.google.com/chart?chco=ff0000,00ff00,aa00ff,99FF00&chf=bg,lg,0,76A4FB,0,ffffff,1&chd=s:AAAGKEY,ECGBGfZ,BBAABBC,FBABHNJ&chdl=matt|patrick|tim|marck&chtt=SD+Ruby+Fu+level&cht=bvs&chs=300x200&chxr=0,1,234|1,45,300|2,12,22|3,52,132

**Comment by return-null** [comment]
Ah, I realized my issue. I passed a simple array of 7 values for the data, which I had hoped to assign a different color for each, as each is a count for a different person: 
[4, 10, 57, 39, 6, 58, 8]

I passed 7  hex color codes, and 7 users for the legend. But I guess it is not supported to just assign a different color to each bar if there is only one value for that bar?

**Comment by zukunftsalick** [comment]
@return-null I would suggest you ask those questions on stackoverflow :kissing_heart:

**Comment by return-null** [comment]
It is supported. To make it work, I edited gchart.rb, and method "set_bar_colors". I changed this:
@bar_colors = bar_colors.join(',') if bar_colors.is_a?(Array)

To this:
@bar_colors = bar_colors.join('|') if bar_colors.is_a?(Array)

Then it works.
