### ISSUE TITLE
Generate PNG url?

### ISSUE THREAD

**Issue by Deekor** [mattetti/googlecharts#78]
Does this gem support generating the PNG url of a chart so I can include it in a email?

https://developers.google.com/chart/interactive/docs/printing

**Comment by zukunftsalick** [comment]
@Deekor 
yes. it works.

eg:
http://chart.apis.google.com/chart?chtt=title\nsubtitle&chs=300x200&cht=lc&chd=t:10,5.2,4,45,78

![image example](http://chart.apis.google.com/chart?chtt=titlensubtitle&chs=300x200&cht=lc&chd=t:10,5.2,4,45,78)
