### ISSUE TITLE
Stacked bar not coming properly

### ISSUE THREAD

**Issue by harikesh11492** [mattetti/googlecharts#80]
With gem googlecharts when tried to create the stacked bar chart , getting same charts for both the :stacked=> true and :stacked=>false.

```
require 'gchart'
Gchart.bar(:data => [[300, 100, 30, 200], [100, 200, 300, 10]], :bar_colors => ['FF0000', '00FF00'],:filename=>"/tmp/test2.png",:stacked => false)
```

The output is  "http://chart.apis.google.com/chart?chco=FF0000,00FF00&chd=s:uPEf,PfuB&cht=bvs&chs=300x200&chxr=0,300,300|1,100,300"

```
require 'gchart'
Gchart.bar(:data => [[300, 100, 30, 200], [100, 200, 300, 10]], :bar_colors => ['FF0000', '00FF00'],:filename=>"/tmp/test2.png",:stacked => true)
```

The output is  "http://chart.apis.google.com/chart?chco=FF0000,00FF00&chd=s:uPEf,PfuB&cht=bvs&chs=300x200&chxr=0,300,300|1,100,300"

The ruby version is 1.9.3-p385 and gem version is 1.6.12 (also tested in 1.6.10)

**Comment by zukunftsalick** [comment]
they look stacked for me. What do you want to achieve? Can you show something visual?

**Comment by harikesh11492** [comment]
Thanks for looking into it.
I was following the steps given in [https://matt.aimonetti.net/googlecharts/](url) 
I was trying to create the unstacked bar chart 
![image](https://cloud.githubusercontent.com/assets/12443965/14842078/a170ef62-0c61-11e6-96db-c51fba6aa441.png)

But for :stacked=> true and :stacked=>false i was getting the below chart
![image](https://cloud.githubusercontent.com/assets/12443965/14842060/7d93828a-0c61-11e6-8188-d20f7f5e33a1.png)

As you can see in my previous comment , both stacked and unstacked giving me same output (is stacked output)
[http://chart.apis.google.com/chart?chco=FF0000,00FF00&chd=s:uPEf,PfuB&cht=bvs&chs=300x200&chxr=0,300,300%7C1,100,300](url)

**Comment by zukunftsalick** [comment]
Now I got it.  

Please set the parameter `:orientation => 'horizontal'` to get the bars non-stacked.

hope that works for you @harikesh11492 

You can check the specs that cover this case at https://github.com/mattetti/googlecharts/blob/d316458ad177369d5deda5d16513bd3d2e06478d/spec/gchart_spec.rb#L308

URL: http://chart.apis.google.com/chart?chco=FF0000,00FF00&chd=s:uPEf,PfuB&cht=bhs&chs=300x200&chxr=0,300,300|1,100,300

**Comment by harikesh11492** [comment]
@zukunftsalick : I want to create the the vertical chart with unstacked way like the below one 
![image](https://cloud.githubusercontent.com/assets/12443965/14845347/38d74658-0c7b-11e6-94fd-331c172c5e00.png)
for which i used the code 
`Gchart.bar(:data => [[300, 100, 30, 200], [100, 200, 300, 10]], 
           :bar_colors => 'FF0000,00FF00',
           :stacked => false )`
With orientation change also i am still getting the stacked chart with horizontal orientation(which is not what i need)
[http://chart.apis.google.com/chart?chco=FF0000,00FF00&chd=s:uPEf,PfuB&cht=bhs&chs=300x200&chxr=0,300,300%7C1,100,300](url)

![image](https://cloud.githubusercontent.com/assets/12443965/14845376/694e82c4-0c7b-11e6-80c6-6b023d9c9f66.png)

**Comment by zukunftsalick** [comment]
look at the method `bar_presentation` on https://github.com/mattetti/googlecharts/blob/master/lib/gchart.rb#L136

there's no `stacked` parameter there since a refactor in 2012 so what I did was to set `:grouped => true` and then I get the graph you want. 

code:
`Gchart.bar(:data => [[300, 100, 30, 200], [100, 200, 300, 10]], :bar_colors => 'FF0000,00FF00', :grouped => true)`

graph:
![graph](http://chart.apis.google.com/chart?chco=FF0000,00FF00&chd=s:9UGp,Up9C&cht=bvg&chs=300x200&chxr=0,300,300|1,100,300)

**Comment by harikesh11492** [comment]
Thanks for the code.It fixed my issue 
It seems the documentation https://matt.aimonetti.net/googlecharts/ has was of older gem versions
